import {
  CSRProject,
  Proposal,
  ProposalEvaluation,
  Contract,
  Payment,
  Fulfillment,
  NGOVerification,
  AIVerification,
  ImpactReport,
  Notification,
  AuditLog,
  Organization,
  Profile,
  Tender,
  TenderQuotation,
  QuotationEvaluation,
  OrgVerification,
  NGONeedAnalysis,
} from '@/types';

// ─── PROFILES ─────────────────────────────────────────────────────────────────
export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'prof-ngo-1',
    auth_user_id: 'auth-ngo-1',
    name: 'Ananya Sharma',
    email: 'ananya@shikshafoundation.org',
    role: 'NGO',
    organization_id: 'org-ngo-1',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'prof-corp-1',
    auth_user_id: 'auth-corp-1',
    name: 'Rajesh Verma',
    email: 'rajesh.verma@apextech.com',
    role: 'CORPORATE',
    organization_id: 'org-corp-1',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'prof-biz-1',
    auth_user_id: 'auth-biz-1',
    name: 'Vikram Patel',
    email: 'vikram@greengrowsupplies.com',
    role: 'BUSINESS',
    organization_id: 'org-biz-1',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'prof-biz-2',
    auth_user_id: 'auth-biz-2',
    name: 'Priya Nair',
    email: 'priya@techedu.in',
    role: 'BUSINESS',
    organization_id: 'org-biz-2',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'prof-biz-3',
    auth_user_id: 'auth-biz-3',
    name: 'Rahul Mehta',
    email: 'rahul@rapidlogistics.com',
    role: 'BUSINESS',
    organization_id: 'org-biz-3',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'prof-admin-1',
    auth_user_id: 'auth-admin-1',
    name: 'IRISiv Lead Auditor',
    email: 'admin@irisiv.org',
    role: 'ADMIN',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

// ─── ORGANIZATIONS ────────────────────────────────────────────────────────────
export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-ngo-1',
    name: 'Shiksha Foundation India',
    organization_type: 'NGO',
    location: 'Ahmedabad, Gujarat',
    phone: '+91-79-2630-1234',
    verification_status: 'VERIFIED',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'org-corp-1',
    name: 'Apex Global Technologies',
    organization_type: 'CORPORATE',
    location: 'Mumbai, Maharashtra',
    phone: '+91-22-6743-9000',
    verification_status: 'VERIFIED',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'org-biz-1',
    name: 'GreenGrow Educational Supplies Ltd',
    organization_type: 'BUSINESS',
    location: 'Ahmedabad, Gujarat',
    phone: '+91-98250-11234',
    verification_status: 'VERIFIED',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'org-biz-2',
    name: 'TechEdu Solutions Pvt Ltd',
    organization_type: 'BUSINESS',
    location: 'Pune, Maharashtra',
    phone: '+91-20-6601-7788',
    verification_status: 'VERIFIED',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'org-biz-3',
    name: 'RapidLogistics & Vendors',
    organization_type: 'BUSINESS',
    location: 'Surat, Gujarat',
    phone: '+91-98765-44321',
    verification_status: 'VERIFIED',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];

// ─── ORG VERIFICATIONS ────────────────────────────────────────────────────────
export const INITIAL_ORG_VERIFICATIONS: OrgVerification[] = [
  {
    id: 'orgver-ngo-1',
    organization_id: 'org-ngo-1',
    status: 'VERIFIED',
    documents: [
      { id: 'doc-1', verification_id: 'orgver-ngo-1', document_type: '12A Certificate', file_name: '12A_Certificate.pdf', storage_path: 'docs/org-ngo-1/12a.pdf', uploaded_at: new Date(Date.now() - 35 * 86400000).toISOString() },
      { id: 'doc-2', verification_id: 'orgver-ngo-1', document_type: '80G Certificate', file_name: '80G_Certificate.pdf', storage_path: 'docs/org-ngo-1/80g.pdf', uploaded_at: new Date(Date.now() - 35 * 86400000).toISOString() },
      { id: 'doc-3', verification_id: 'orgver-ngo-1', document_type: 'PAN Card', file_name: 'PAN_Organisation.pdf', storage_path: 'docs/org-ngo-1/pan.pdf', uploaded_at: new Date(Date.now() - 35 * 86400000).toISOString() },
    ],
    ai_screening_result: {
      id: 'screening-ngo-1',
      verification_id: 'orgver-ngo-1',
      extracted_data: { name: 'Shiksha Foundation India', pan: 'AAATS1234C', registration: 'E/12345/Ahmedabad' },
      identified_document_types: ['12A Certificate', '80G Certificate', 'PAN Card'],
      completeness_score: 96,
      consistency_check: 'All organization names match across documents.',
      issues: [],
      warnings: [],
      recommendation: 'PROCEED_TO_LEGAL_REVIEW',
      screening_summary: 'All three required documents present. Names consistent across all records. No anomalies detected. Recommend proceeding to legal compliance review.',
      ai_powered: true,
      created_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    },
    reviewer_id: 'prof-admin-1',
    reviewer_decision: 'APPROVE',
    reviewer_comments: 'All documents valid and consistent. Organization approved.',
    reviewed_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

// ─── NGO NEED ANALYSIS ────────────────────────────────────────────────────────
export const INITIAL_NEED_ANALYSES: NGONeedAnalysis[] = [
  {
    id: 'need-dlc-1',
    project_id: 'proj-dlc',
    original_description: 'We have 150 children at our learning center in Rajkot but we do not have enough computers for digital education. The children are between 10-16 years old and need basic computer literacy and internet access for STEM subjects. We need computers, installation, and teacher training.',
    structured_title: 'Digital Learning Center — Computer Lab Setup',
    category: 'EDUCATION',
    problem_summary: 'Shiksha Foundation\'s Rajkot center lacks adequate computer infrastructure for 150 students aged 10–16, limiting digital education and STEM learning opportunities.',
    beneficiary_group: 'School-age children (10–16 years) at Shiksha Foundation Learning Center',
    estimated_beneficiaries: 150,
    location: 'Rajkot, Gujarat',
    required_items: [
      { item: 'Desktop Computers', quantity: 20, specification: 'Minimum Intel Core i5, 8GB RAM, 512GB SSD, Windows 11 Pro, 21.5" monitor' },
      { item: 'Internet Connectivity Setup', quantity: 1, specification: 'Broadband connection with 100 Mbps, router, structured cabling for 20 nodes' },
      { item: 'Computer Lab Furniture', quantity: 20, specification: '20 computer desks with ergonomic chairs suitable for 10–16 year olds' },
      { item: 'Teacher Training Program', quantity: 1, specification: '3-day intensive digital literacy and STEM teaching methodology training for 5 teachers' },
      { item: '1-Year Annual Maintenance Contract', quantity: 1, specification: 'On-site support with 24-hour response time for all hardware and network issues' },
    ],
    estimated_budget: 185000,
    suggested_timeline_days: 45,
    urgency: 'HIGH',
    expected_impact: '150 students will gain foundational digital literacy and STEM skills, improving their academic performance and long-term employability. 5 teachers will be equipped with modern digital teaching tools.',
    csr_category: 'Education & Digital Inclusion',
    csr_eligibility_indicators: [
      'Promotes education (Schedule VII, Clause (ii))',
      'Serves economically disadvantaged youth',
      'Rural/semi-urban location qualifies for CSR priority',
      'Non-profit organization beneficiary',
    ],
    missing_information: [],
    ai_powered: true,
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
  },
];

// ─── PROJECTS ─────────────────────────────────────────────────────────────────
export const INITIAL_PROJECTS: CSRProject[] = [
  // FLAGSHIP: Digital Learning Center — main demo project at ADVANCE_20_PAID/IN_PROGRESS
  {
    id: 'proj-dlc',
    project_code: 'CSR-1028',
    title: 'Digital Learning Center — Computer Lab Setup',
    category: 'EDUCATION',
    fulfillment_type: 'PRODUCT',
    location: 'Rajkot, Gujarat',
    description: 'Setting up a fully equipped 20-computer lab with internet connectivity, lab furniture, teacher training, and 1-year maintenance for 150 students aged 10–16 at Shiksha Foundation\'s learning center.',
    beneficiaries: 150,
    estimated_budget: 185000,
    contract_value: 183000,
    deadline: '2026-09-30',
    status: 'ADVANCE_20_PAID',
    urgency: 'HIGH',
    ngo_organization_id: 'org-ngo-1',
    corporate_organization_id: 'org-corp-1',
    selected_business_organization_id: 'org-biz-1',
    tender_id: 'tender-dlc',
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  // Tender open — water systems
  {
    id: 'proj-1021',
    project_code: 'CSR-1021',
    title: 'Clean Drinking Water Systems for Tribal Schools',
    category: 'WATER & SANITATION',
    fulfillment_type: 'PRODUCT',
    location: 'Dangs, Gujarat',
    description: 'Installation of solar-powered reverse osmosis water purification plants across 5 primary schools in tribal districts. Each plant capable of producing 500L/day of clean drinking water.',
    beneficiaries: 1200,
    estimated_budget: 150000,
    deadline: '2026-10-15',
    status: 'TENDER_OPEN',
    urgency: 'HIGH',
    ngo_organization_id: 'org-ngo-1',
    corporate_organization_id: 'org-corp-1',
    tender_id: 'tender-water',
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  // Submitted — awaiting corporate
  {
    id: 'proj-1022',
    project_code: 'CSR-1022',
    title: 'Mobile Medical Camp for Senior Citizens',
    category: 'HEALTHCARE',
    fulfillment_type: 'SERVICE',
    location: 'Rajkot, Gujarat',
    description: 'Monthly mobile medical camps providing free health checkups, medicines, and physiotherapy services to senior citizens in rural areas. Targeting 300 beneficiaries per month for 6 months.',
    beneficiaries: 300,
    estimated_budget: 90000,
    deadline: '2027-03-31',
    status: 'SUBMITTED',
    urgency: 'MEDIUM',
    ngo_organization_id: 'org-ngo-1',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  // AI verified — ready for final payment
  {
    id: 'proj-1025',
    project_code: 'CSR-1025',
    title: 'Midday Meal Nutrition Kits for Primary Schools',
    category: 'HEALTH & NUTRITION',
    fulfillment_type: 'PRODUCT',
    location: 'Vadodara Rural',
    description: 'Provision of fortified food packets and sanitization kits to primary school canteens serving 500 children. Each kit contains month-supply of fortified dal, rice, vitamins, and hygiene products.',
    beneficiaries: 500,
    estimated_budget: 60000,
    contract_value: 58000,
    deadline: '2026-08-20',
    status: 'NGO_CONFIRMED',
    urgency: 'MEDIUM',
    ngo_organization_id: 'org-ngo-1',
    corporate_organization_id: 'org-corp-1',
    selected_business_organization_id: 'org-biz-1',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  // Completed — with full impact report
  {
    id: 'proj-1026',
    project_code: 'CSR-1026',
    title: 'Solar Lanterns for Remote Villages',
    category: 'RENEWABLE ENERGY',
    fulfillment_type: 'PRODUCT',
    location: 'Kutch, Gujarat',
    description: 'Deploying 300 high-efficiency solar household lights to off-grid rural households. Each unit generates 8 hours of light per night with 3-year warranty.',
    beneficiaries: 300,
    estimated_budget: 45000,
    contract_value: 45000,
    deadline: '2026-07-31',
    status: 'COMPLETED',
    urgency: 'LOW',
    ngo_organization_id: 'org-ngo-1',
    corporate_organization_id: 'org-corp-1',
    selected_business_organization_id: 'org-biz-1',
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  // Manual review — disputed quantity
  {
    id: 'proj-1027',
    project_code: 'CSR-1027',
    title: 'Flood Relief Rations & Emergency Blanket Drive',
    category: 'DISASTER RELIEF',
    fulfillment_type: 'PRODUCT',
    location: 'Surat Coastal Area',
    description: 'Emergency supply of 1,000 ration kits and heavy fleece blankets for flood-affected families. Priority distribution to households with elderly and children.',
    beneficiaries: 1000,
    estimated_budget: 100000,
    contract_value: 95000,
    deadline: '2026-08-15',
    status: 'MANUAL_REVIEW',
    urgency: 'CRITICAL',
    ngo_organization_id: 'org-ngo-1',
    corporate_organization_id: 'org-corp-1',
    selected_business_organization_id: 'org-biz-3',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  // Skill development — draft with AI analysis
  {
    id: 'proj-1029',
    project_code: 'CSR-1029',
    title: 'Vocational Skill Training for Youth',
    category: 'SKILL DEVELOPMENT',
    fulfillment_type: 'SERVICE',
    location: 'Ahmedabad, Gujarat',
    description: 'A 3-month intensive vocational training program for 100 unemployed youth aged 18–25. Covers mobile repair, electrical work, plumbing, and carpentry with placement support.',
    beneficiaries: 100,
    estimated_budget: 75000,
    deadline: '2027-01-31',
    status: 'NGO_REVIEW',
    urgency: 'MEDIUM',
    ngo_organization_id: 'org-ngo-1',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

// ─── TENDERS ──────────────────────────────────────────────────────────────────
export const INITIAL_TENDERS: Tender[] = [
  // Flagship DLC tender — business selected, closed
  {
    id: 'tender-dlc',
    tender_code: 'TND-1028',
    project_id: 'proj-dlc',
    corporate_organization_id: 'org-corp-1',
    title: 'Digital Learning Center Computer Lab Setup',
    category: 'EDUCATION',
    fulfillment_type: 'PRODUCT',
    required_quantity: 20,
    unit: 'Computer Units',
    minimum_specifications: 'Intel Core i5 12th Gen, 8GB DDR4 RAM, 512GB SSD, Windows 11 Pro, 21.5" Full HD Monitor, Webcam, Keyboard & Mouse. 3-year on-site warranty minimum.',
    budget: 185000,
    delivery_location: 'Shiksha Foundation, 45 Education Colony, Rajkot - 360001',
    deadline: '2026-09-30',
    delivery_timeline_days: 30,
    payment_terms: '20% Advance on contract execution. 40% Fulfillment Milestone on delivery proof submission. 40% Final after NGO physical confirmation.',
    additional_requirements: 'Vendor must provide installation, cabling, and configuration. Teacher training for 5 staff (3 days). 1-year annual maintenance contract included.',
    open_date: new Date(Date.now() - 18 * 86400000).toISOString(),
    closing_date: new Date(Date.now() - 8 * 86400000).toISOString(),
    status: 'BUSINESS_SELECTED',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  // Water systems tender — open for quotations
  {
    id: 'tender-water',
    tender_code: 'TND-1021',
    project_id: 'proj-1021',
    corporate_organization_id: 'org-corp-1',
    title: 'Solar RO Water Purification Plants for Tribal Schools',
    category: 'WATER & SANITATION',
    fulfillment_type: 'PRODUCT',
    required_quantity: 5,
    unit: 'RO Plant Units',
    minimum_specifications: 'Solar-powered RO system, 500L/day capacity, TDS reduction to <50ppm, auto-flush feature, stainless steel body, 5-year warranty on membranes.',
    budget: 150000,
    delivery_location: '5 Schools, Dangs District, Gujarat (delivery to each site)',
    deadline: '2026-10-15',
    delivery_timeline_days: 45,
    payment_terms: '20% Advance. 40% after installation & commissioning proof. 40% after NGO 30-day operational confirmation.',
    additional_requirements: 'Installation at each of 5 school sites. Training of school staff for operation and basic maintenance.',
    open_date: new Date(Date.now() - 5 * 86400000).toISOString(),
    closing_date: new Date(Date.now() + 10 * 86400000).toISOString(),
    status: 'OPEN',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

// ─── TENDER QUOTATIONS ────────────────────────────────────────────────────────
export const INITIAL_QUOTATIONS: TenderQuotation[] = [
  // DLC Tender — GreenGrow (SELECTED — AI Recommended)
  {
    id: 'quot-dlc-1',
    tender_id: 'tender-dlc',
    project_id: 'proj-dlc',
    business_organization_id: 'org-biz-1',
    bid_amount: 183000,
    delivery_timeline_days: 21,
    quantity_offered: 20,
    specifications_offered: 'Dell OptiPlex 5000 (Intel Core i5-12th Gen, 16GB RAM, 512GB NVMe SSD, Windows 11 Pro, 22" Full HD IPS Monitor, Webcam, BT Keyboard & Mouse). 3-year on-site NBD warranty.',
    capacity: 'ISO 9001:2015 certified supply chain. 200+ unit fulfillment capacity per month. Direct Dell partner for Gujarat region.',
    experience: 'Completed 18 government and NGO digital classroom projects in Gujarat (2020–2025). References available from GCERT and GSWAN.',
    description: 'Comprehensive turnkey computer lab setup including delivery, installation, network cabling, OS configuration, educational software pre-installation, and 3-day staff training. 1-year AMC included.',
    warranty_guarantee: '3-year on-site warranty. Dell ProSupport coverage. 1-year AMC post-warranty.',
    terms: 'Payment as per tender terms. Delivery guaranteed by Day 21 or price reduction of 0.5% per day.',
    status: 'SELECTED',
    requirement_match_pct: 97,
    submitted_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  // DLC Tender — TechEdu Solutions
  {
    id: 'quot-dlc-2',
    tender_id: 'tender-dlc',
    project_id: 'proj-dlc',
    business_organization_id: 'org-biz-2',
    bid_amount: 171000,
    delivery_timeline_days: 35,
    quantity_offered: 20,
    specifications_offered: 'Assembled Systems (Intel Core i5-12th Gen, 8GB DDR4 RAM, 512GB SSD, Windows 11 Home, 21.5" Full HD VA Monitor). 2-year warranty.',
    capacity: 'Can supply up to 50 systems per month. In-house assembly unit in Pune.',
    experience: '5 years in B2B electronics supply. 3 educational institution projects.',
    description: 'Standard computer supply with basic setup. Training not included — can be arranged separately at additional cost.',
    warranty_guarantee: '2-year warranty. Parts replacement within 72 hours.',
    status: 'REJECTED',
    requirement_match_pct: 78,
    submitted_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  // DLC Tender — RapidLogistics
  {
    id: 'quot-dlc-3',
    tender_id: 'tender-dlc',
    project_id: 'proj-dlc',
    business_organization_id: 'org-biz-3',
    bid_amount: 162000,
    delivery_timeline_days: 28,
    quantity_offered: 20,
    specifications_offered: 'Lenovo ThinkCentre M70s (Intel Core i5-11th Gen, 8GB RAM, 256GB SSD, Windows 11 Pro, 20" Monitor). 1-year warranty.',
    capacity: 'General logistics and supply. Electronics experience limited.',
    experience: '2 years logistics. First educational technology project.',
    description: 'Supply of computers with delivery. Installation and training would require subcontracting at additional cost.',
    warranty_guarantee: '1-year warranty through manufacturer.',
    status: 'REJECTED',
    requirement_match_pct: 62,
    submitted_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  // Water tender — quotation submitted (tender still open)
  {
    id: 'quot-water-1',
    tender_id: 'tender-water',
    project_id: 'proj-1021',
    business_organization_id: 'org-biz-1',
    bid_amount: 142000,
    delivery_timeline_days: 40,
    quantity_offered: 5,
    specifications_offered: 'Aquatech Solar-RO 500L system. Solar panel 200W, 100L storage tank, 5-stage filtration, TDS meter built-in. 5-year membrane warranty.',
    capacity: 'Authorized Aquatech distributor for Gujarat. Previous installations in 12 schools.',
    experience: 'Water treatment solutions for 8 years. 35+ installations across rural Gujarat.',
    description: 'Complete turnkey installation including civil work for RO mounting, solar panel installation, plumbing connections, staff training, and quarterly service for 1 year.',
    warranty_guarantee: '5-year membrane warranty. Annual service contract included.',
    status: 'SUBMITTED',
    requirement_match_pct: 95,
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

// ─── QUOTATION EVALUATIONS ────────────────────────────────────────────────────
export const INITIAL_QUOTATION_EVALUATIONS: QuotationEvaluation[] = [
  {
    id: 'qeval-dlc-1',
    quotation_id: 'quot-dlc-1',
    tender_id: 'tender-dlc',
    price_score: 88,
    requirement_match_score: 97,
    timeline_score: 96,
    capacity_score: 98,
    experience_score: 96,
    feasibility_score: 95,
    verification_score: 100,
    overall_score: 95.7,
    recommendation: 'STRONG CANDIDATE (AI Recommended)',
    reasoning: 'GreenGrow fully meets and exceeds minimum specifications (16GB RAM vs required 8GB, 3-year warranty vs required). Fastest delivery at 21 days. Strongest verified track record in Gujarat educational sector with 18 completed projects. Turnkey offering includes everything required — installation, training, and AMC. Highest overall score across all evaluation factors.',
    ai_powered: true,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'qeval-dlc-2',
    quotation_id: 'quot-dlc-2',
    tender_id: 'tender-dlc',
    price_score: 95,
    requirement_match_score: 78,
    timeline_score: 80,
    capacity_score: 82,
    experience_score: 74,
    feasibility_score: 79,
    verification_score: 100,
    overall_score: 83.8,
    recommendation: 'ACCEPTABLE CANDIDATE',
    reasoning: 'Lower cost but offers Windows 11 Home (not Pro as required), only 8GB RAM, 2-year warranty vs required 3 years. Training not included — increases risk of poor adoption. Limited educational sector experience. Longer delivery timeline of 35 days.',
    ai_powered: true,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'qeval-dlc-3',
    quotation_id: 'quot-dlc-3',
    tender_id: 'tender-dlc',
    price_score: 97,
    requirement_match_score: 62,
    timeline_score: 84,
    capacity_score: 58,
    experience_score: 48,
    feasibility_score: 65,
    verification_score: 100,
    overall_score: 73.4,
    recommendation: 'RISKY CANDIDATE',
    reasoning: 'Lowest price but significant specification gaps: 11th Gen Intel (not 12th), 256GB SSD (insufficient), 1-year warranty only, 20" monitor. No experience in educational technology projects. Training and installation not offered directly — subcontracting risk. Recommendation: Do not select.',
    ai_powered: true,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
];

// ─── OLD PROPOSALS (backward compat) ──────────────────────────────────────────
export const INITIAL_PROPOSALS: Proposal[] = [];
export const INITIAL_EVALUATIONS: Record<string, ProposalEvaluation> = {};

// ─── CONTRACTS ────────────────────────────────────────────────────────────────
export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'contract-dlc',
    project_id: 'proj-dlc',
    tender_id: 'tender-dlc',
    corporate_organization_id: 'org-corp-1',
    business_organization_id: 'org-biz-1',
    amount: 183000,
    scope: 'Supply, delivery, installation and configuration of 20 desktop computers with full network setup, teacher training, and 1-year AMC for Shiksha Foundation Digital Learning Center, Rajkot.',
    fulfillment_requirements: 'All 20 units must be installed and operational. Network must be tested. 5 teachers must complete training. Completion report with photos required.',
    terms: '20% Advance (₹36,600) on contract execution. 40% Fulfillment Milestone (₹73,200) after delivery and installation proof. 40% Final (₹73,200) after NGO physical confirmation. All payments simulated within IRISiv platform.',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'contract-1025',
    project_id: 'proj-1025',
    corporate_organization_id: 'org-corp-1',
    business_organization_id: 'org-biz-1',
    amount: 58000,
    scope: 'Supply of 500 fortified nutrition and hygiene kits for primary school children in Vadodara rural schools.',
    terms: '20% Advance (₹11,600). 40% Fulfillment Milestone (₹23,200) after delivery proof. 40% Final (₹23,200) after NGO confirmation.',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
  },
  {
    id: 'contract-1026',
    project_id: 'proj-1026',
    corporate_organization_id: 'org-corp-1',
    business_organization_id: 'org-biz-1',
    amount: 45000,
    scope: 'Supply and distribution of 300 solar household lanterns to off-grid villages in Kutch district.',
    terms: '20% Advance (₹9,000). 40% Fulfillment (₹18,000). 40% Final (₹18,000).',
    status: 'COMPLETED',
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'contract-1027',
    project_id: 'proj-1027',
    corporate_organization_id: 'org-corp-1',
    business_organization_id: 'org-biz-3',
    amount: 95000,
    scope: 'Supply and distribution of 1,000 flood relief ration kits and blankets to flood-affected families in Surat coastal area.',
    terms: '20% Advance (₹19,000). 40% Fulfillment (₹38,000). 40% Final (₹38,000) — pending manual review.',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

// ─── PAYMENTS — 20% + 40% + 40% ──────────────────────────────────────────────
export const INITIAL_PAYMENTS: Payment[] = [
  // DLC: 20% advance paid
  {
    id: 'pay-dlc-adv',
    project_id: 'proj-dlc',
    contract_id: 'contract-dlc',
    payment_type: 'ADVANCE_20',
    amount: 36600,  // 20% of 183,000
    percentage: 20,
    milestone_label: '20% Advance',
    status: 'RECORDED',
    trigger_condition: 'Contract execution confirmed',
    approved_by: 'prof-corp-1',
    approved_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  // 1025: advance + milestone paid, awaiting final
  {
    id: 'pay-1025-adv',
    project_id: 'proj-1025',
    contract_id: 'contract-1025',
    payment_type: 'ADVANCE_20',
    amount: 11600,  // 20% of 58,000
    percentage: 20,
    milestone_label: '20% Advance',
    status: 'RECORDED',
    trigger_condition: 'Contract execution confirmed',
    approved_by: 'prof-corp-1',
    approved_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'pay-1025-mil',
    project_id: 'proj-1025',
    contract_id: 'contract-1025',
    payment_type: 'FULFILLMENT_40',
    amount: 23200,  // 40% of 58,000
    percentage: 40,
    milestone_label: '40% Fulfillment Milestone',
    status: 'RECORDED',
    trigger_condition: 'Fulfillment proof verified by system',
    approved_by: 'prof-corp-1',
    approved_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  // 1026: all 3 payments complete
  {
    id: 'pay-1026-adv',
    project_id: 'proj-1026',
    contract_id: 'contract-1026',
    payment_type: 'ADVANCE_20',
    amount: 9000,
    percentage: 20,
    milestone_label: '20% Advance',
    status: 'RECORDED',
    trigger_condition: 'Contract execution confirmed',
    approved_by: 'prof-corp-1',
    approved_at: new Date(Date.now() - 38 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 38 * 86400000).toISOString(),
  },
  {
    id: 'pay-1026-mil',
    project_id: 'proj-1026',
    contract_id: 'contract-1026',
    payment_type: 'FULFILLMENT_40',
    amount: 18000,
    percentage: 40,
    milestone_label: '40% Fulfillment Milestone',
    status: 'RECORDED',
    trigger_condition: 'Fulfillment proof verified',
    approved_by: 'prof-corp-1',
    approved_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'pay-1026-fin',
    project_id: 'proj-1026',
    contract_id: 'contract-1026',
    payment_type: 'FINAL_40',
    amount: 18000,
    percentage: 40,
    milestone_label: '40% Final',
    status: 'RECORDED',
    trigger_condition: 'NGO physical confirmation received',
    approved_by: 'prof-corp-1',
    approved_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  // 1027: advance paid, milestone under review
  {
    id: 'pay-1027-adv',
    project_id: 'proj-1027',
    contract_id: 'contract-1027',
    payment_type: 'ADVANCE_20',
    amount: 19000,
    percentage: 20,
    milestone_label: '20% Advance',
    status: 'RECORDED',
    trigger_condition: 'Contract execution confirmed',
    approved_by: 'prof-corp-1',
    approved_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
];

// ─── FULFILLMENTS ─────────────────────────────────────────────────────────────
export const INITIAL_DELIVERIES: Fulfillment[] = [
  // 1025: successful fulfillment
  {
    id: 'del-1025',
    project_id: 'proj-1025',
    business_organization_id: 'org-biz-1',
    fulfillment_type: 'PRODUCT',
    quantity_delivered: 500,
    delivery_date: '2026-08-08',
    quality: 'EXCELLENT',
    comments: 'Delivered 500 sealed nutrition & hygiene kits to Vadodara central school warehouse. All kits inspected before dispatch.',
    submitted_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    evidence: [
      {
        id: 'ev-1025-1',
        delivery_id: 'del-1025',
        evidence_type: 'INVOICE',
        storage_path: 'fulfillments/del-1025/invoice.pdf',
        file_name: 'Tax_Invoice_GGS_INV58000.pdf',
        mime_type: 'application/pdf',
        uploaded_by: 'prof-biz-1',
        created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
      },
      {
        id: 'ev-1025-2',
        delivery_id: 'del-1025',
        evidence_type: 'FULFILLMENT_RECEIPT',
        storage_path: 'fulfillments/del-1025/receipt.pdf',
        file_name: 'Signed_Delivery_Challan_500kits.pdf',
        mime_type: 'application/pdf',
        uploaded_by: 'prof-biz-1',
        created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
      },
      {
        id: 'ev-1025-3',
        delivery_id: 'del-1025',
        evidence_type: 'PHOTO',
        storage_path: 'fulfillments/del-1025/handover.jpg',
        file_name: 'Warehouse_Handover_Photo_500kits.jpg',
        mime_type: 'image/jpeg',
        uploaded_by: 'prof-biz-1',
        created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
      },
    ],
  },
  // 1026: completed fulfillment
  {
    id: 'del-1026',
    project_id: 'proj-1026',
    business_organization_id: 'org-biz-1',
    fulfillment_type: 'PRODUCT',
    quantity_delivered: 300,
    delivery_date: '2026-07-25',
    quality: 'EXCELLENT',
    comments: 'All 300 solar lanterns delivered and installed at households in Kutch. Demonstration provided to each family.',
    submitted_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    evidence: [
      {
        id: 'ev-1026-1',
        delivery_id: 'del-1026',
        evidence_type: 'INVOICE',
        storage_path: 'fulfillments/del-1026/invoice.pdf',
        file_name: 'Invoice_Solar_Lanterns_300units.pdf',
        mime_type: 'application/pdf',
        uploaded_by: 'prof-biz-1',
        created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
      },
    ],
  },
  // 1027: disputed — 950 of 1000
  {
    id: 'del-1027',
    project_id: 'proj-1027',
    business_organization_id: 'org-biz-3',
    fulfillment_type: 'PRODUCT',
    quantity_delivered: 950,
    delivery_date: '2026-08-07',
    quality: 'GOOD',
    comments: 'Delivered 950 ration kits & blankets. 50 units could not be reached due to temporary road closure in flood zone. Will supply remaining 50 within 72 hours.',
    submitted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    evidence: [
      {
        id: 'ev-1027-1',
        delivery_id: 'del-1027',
        evidence_type: 'INVOICE',
        storage_path: 'fulfillments/del-1027/invoice-950.pdf',
        file_name: 'Partial_Invoice_950_kits.pdf',
        mime_type: 'application/pdf',
        uploaded_by: 'prof-biz-3',
        created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
    ],
  },
];

// ─── NGO VERIFICATIONS ────────────────────────────────────────────────────────
export const INITIAL_NGO_VERIFICATIONS: NGOVerification[] = [
  {
    id: 'ngo-ver-1025',
    project_id: 'proj-1025',
    delivery_id: 'del-1025',
    quantity_received: 500,
    delivery_date: '2026-08-08',
    quality_acceptable: true,
    packaging_acceptable: true,
    delivered_on_time: true,
    invoice_reference: 'GGS-INV58000',
    comments: 'Inspected all 500 kits. All items intact, properly sealed, within expiry date. Fully satisfied. Certified for final payment release.',
    has_issue: false,
    authorized_representative_confirmed: true,
    submitted_by: 'prof-ngo-1',
    submitted_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'ngo-ver-1026',
    project_id: 'proj-1026',
    delivery_id: 'del-1026',
    quantity_received: 300,
    delivery_date: '2026-07-25',
    quality_acceptable: true,
    packaging_acceptable: true,
    delivered_on_time: true,
    invoice_reference: 'GGS-SOLAR-300',
    comments: 'All 300 solar lanterns received and operational. Community extremely satisfied. 100% household coverage achieved.',
    has_issue: false,
    authorized_representative_confirmed: true,
    submitted_by: 'prof-ngo-1',
    submitted_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'ngo-ver-1027',
    project_id: 'proj-1027',
    delivery_id: 'del-1027',
    quantity_received: 950,
    delivery_date: '2026-08-07',
    quality_acceptable: true,
    packaging_acceptable: true,
    delivered_on_time: false,
    invoice_reference: 'RL-SURAT-950',
    comments: 'Received 950 of 1,000 kits. 50 units missing. Vendor claims they will deliver within 72 hours due to road closure.',
    has_issue: true,
    issue_description: 'Shortfall of 50 units (5%). Vendor explanation noted but final 40% payment should be withheld until all 1,000 units confirmed received.',
    authorized_representative_confirmed: true,
    submitted_by: 'prof-ngo-1',
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

// ─── AI VERIFICATIONS ─────────────────────────────────────────────────────────
export const INITIAL_AI_VERIFICATIONS: AIVerification[] = [
  {
    id: 'ai-ver-1025',
    project_id: 'proj-1025',
    ngo_verification_id: 'ngo-ver-1025',
    status: 'LIKELY_FULFILLED',
    confidence: 0.97,
    requested_quantity: 500,
    received_quantity: 500,
    completion_percentage: 100.0,
    issues: [],
    recommendation: '✓ Delivery verified at 100.0% completion. NGO physical check confirmed 500/500 units received. Recommended to release remaining 40% final payment (₹23,200).',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'ai-ver-1026',
    project_id: 'proj-1026',
    ngo_verification_id: 'ngo-ver-1026',
    status: 'LIKELY_FULFILLED',
    confidence: 0.98,
    requested_quantity: 300,
    received_quantity: 300,
    completion_percentage: 100.0,
    issues: [],
    recommendation: '✓ Full delivery confirmed 100%. All 300 solar lanterns verified by NGO physical inspection. Final payment released.',
    created_at: new Date(Date.now() - 11 * 86400000).toISOString(),
  },
  {
    id: 'ai-ver-1027',
    project_id: 'proj-1027',
    ngo_verification_id: 'ngo-ver-1027',
    status: 'ISSUE_DETECTED',
    confidence: 0.94,
    requested_quantity: 1000,
    received_quantity: 950,
    completion_percentage: 95.0,
    issues: [
      {
        code: 'QUANTITY_MISMATCH',
        message: 'Discrepancy: 1,000 units contracted, NGO confirmed receipt of only 950 units (50-unit shortfall — 5% gap).',
        expected: 1000,
        actual: 950,
        shortfall: 50,
        shortfallPercentage: 5,
      },
    ],
    recommendation: '⚠ MANUAL REVIEW REQUIRED: 95.0% completion (950/1000 units). Shortfall of 50 units. Corporate review required before releasing final 40% payment. Options: (1) Hold until vendor supplies remaining 50 units, (2) Pro-rate final payment to ₹36,100 (95% of ₹38,000).',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

// ─── IMPACT REPORTS ───────────────────────────────────────────────────────────
export const INITIAL_IMPACT_REPORTS: ImpactReport[] = [
  {
    id: 'report-1026',
    project_id: 'proj-1026',
    ngo_name: 'Shiksha Foundation India',
    corporate_name: 'Apex Global Technologies',
    business_name: 'GreenGrow Educational Supplies Ltd',
    category: 'RENEWABLE ENERGY',
    location: 'Kutch, Gujarat',
    contract_value: 45000,
    payment_advance: 9000,
    payment_milestone: 18000,
    payment_final: 18000,
    beneficiaries: 300,
    requested_quantity: 300,
    delivered_quantity: 300,
    completion_percentage: 100,
    evidence_count: 1,
    verification_status: 'VERIFIED_AND_AUDITED',
    impact_summary: 'IRISiv Verified Impact Report: Project CSR-1026 successfully delivered 300 solar household lanterns to off-grid rural households in Kutch district. All 300 units confirmed by NGO physical inspection with 98% AI confidence. Contract value of ₹45,000 fully disbursed across three payment milestones (₹9,000 advance + ₹18,000 fulfillment + ₹18,000 final). 300 families now have reliable nighttime lighting, improving safety and enabling evening study for 480 estimated children in beneficiary households. Full audit trail maintained in IRISiv immutable ledger.',
    generated_by: 'FeatherlessAI + IRISiv Platform',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────
export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    recipient_profile_id: 'prof-biz-1',
    project_id: 'proj-dlc',
    type: 'ADVANCE_PAYMENT_RECORDED',
    title: '20% Advance Payment Recorded',
    message: 'Project CSR-1028 (Digital Learning Center): ₹36,600 advance payment (20%) has been recorded. You may now begin project execution.',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'notif-2',
    recipient_profile_id: 'prof-corp-1',
    project_id: 'proj-1025',
    type: 'NGO_CONFIRMED',
    title: 'NGO Confirmation Received — Final 40% Ready',
    message: 'Project CSR-1025 (Nutrition Kits): NGO confirmed 100% receipt. Final 40% payment (₹23,200) can now be released.',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'notif-3',
    recipient_profile_id: 'prof-corp-1',
    project_id: 'proj-1027',
    type: 'MISMATCH_DETECTED',
    title: '⚠ Fulfillment Shortfall Flagged — Manual Review',
    message: 'Project CSR-1027 (Flood Relief): NGO reported only 950/1000 units received. AI flagged 5% shortfall. Manual review required before releasing final 40%.',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'notif-4',
    recipient_profile_id: 'prof-biz-1',
    project_id: 'proj-1021',
    type: 'TENDER_PUBLISHED',
    title: 'New Tender: Solar RO Water Systems',
    message: 'Tender TND-1021 for CSR-1021 (Clean Drinking Water Systems) is now open. Budget: ₹1,50,000. Closing: 10 days remaining.',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'notif-5',
    recipient_profile_id: 'prof-ngo-1',
    project_id: 'proj-dlc',
    type: 'BUSINESS_SELECTED',
    title: 'Vendor Selected for Your Project',
    message: 'CSR-1028 (Digital Learning Center): Apex Global Technologies selected GreenGrow Educational Supplies as vendor (AI Score: 95.7/100). Contract value: ₹1,83,000.',
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
];

// ─── AUDIT LOGS ───────────────────────────────────────────────────────────────
export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    project_id: 'proj-dlc',
    actor_profile_id: 'prof-corp-1',
    actor_role: 'CORPORATE',
    action: 'ADVANCE_20_PAYMENT_RECORDED',
    metadata: { amount: 36600, percentage: '20%', contract_id: 'contract-dlc' },
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'audit-2',
    project_id: 'proj-dlc',
    actor_profile_id: 'prof-corp-1',
    actor_role: 'CORPORATE',
    action: 'BUSINESS_SELECTED',
    metadata: { quotation_id: 'quot-dlc-1', ai_score: 95.7, business: 'GreenGrow Educational Supplies Ltd' },
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'audit-3',
    project_id: 'proj-1025',
    actor_profile_id: 'prof-ngo-1',
    actor_role: 'NGO',
    action: 'NGO_FULFILLMENT_CONFIRMED',
    metadata: { quantity_received: 500, status: 'CONFIRMED' },
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'audit-4',
    project_id: 'proj-1027',
    actor_profile_id: 'prof-ngo-1',
    actor_role: 'NGO',
    action: 'NGO_ISSUE_REPORTED',
    metadata: { quantity_received: 950, expected: 1000, shortfall: 50 },
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];
